### ISSUE TITLE
Setup tests for CompatHelper

### ISSUE THREAD

**Issue by lassepe** [JuliaReinforcementLearning/TFRecord.jl#14]
Currently, github actions are not executed for PR's created by `CompatHelper`. There is a guide how to enable them [here](https://juliaregistries.github.io/CompatHelper.jl/dev/#Installation,-step-2:-Set-up-the-SSH-deploy-key). I think it would be nice to have them so that one can see directly in the PR dialog whether the `[compat]` changes broke anything.

**Comment by findmyway** [comment]
Thanks for the suggestion!

I only know this feature for the first time! I set you as the admin of this repo just now. Maybe you can give it a try?
