### ISSUE TITLE
Get rid of unrelated dependencies

### ISSUE THREAD

**Issue by lassepe** [JuliaReinforcementLearning/TFRecord.jl#16]
There seems to be some unrelated code in `src/datasets`. Can these be removed? I think it would be nice to use this package without depending on things like `ImageCore` or `PNGFiles`. Or are these needed for some reason?

**Comment by findmyway** [comment]
Yes, agree. Previously, I'm the only user of this package. So I simply added a submodule to load datasets from some offline RL experiments here under the datasets folder https://github.com/JuliaReinforcementLearning/TFRecord.jl/blob/master/src/datasets/datasets.jl 

Let me have a think of where to put this submodule first. Then I'll remove it from this repo.
