### ISSUE TITLE
ProtoBuf 1.5 compat

### ISSUE THREAD

**Issue by lassepe** [JuliaReinforcementLearning/TFRecord.jl#9]
The `Project.toml` requires Julia 1.6. Is there a specific reason for that? I couldn't find any language features in the source code that would require 1.6.

**Comment by findmyway** [comment]
Hi @lassepe ,

The `Threads.foreach` is used in the Dataset sub module. 

https://docs.julialang.org/en/v1.6.0-rc3/base/multi-threading/#Base.Threads.foreach

But I can change the compat back to Julia@1.3 and manually check the VERSION in that sub module. Will this work for you?

**Comment by lassepe** [comment]
I think it is preferable to have the entire package (including submodules) work for the Julia version specified in the `Project.toml`. Thus, I'd vote against having a manual `VERSION` check in the `Dataset` submodule. Instead, it seems preferable to just use pre 1.6 syntax such as `Threads.@threads`. But if this is not feasible for some reason, I can also switch to Julia 1.6 soon.
